# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre')),
                ('ett', models.CharField(max_length=250, verbose_name='ett a la que pertenece')),
                ('localizacion', models.CharField(max_length=500, verbose_name='localizacion fisica de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_week', models.IntegerField(verbose_name='horas por semana')),
                ('time_contract', models.IntegerField(verbose_name='duracion contrato')),
                ('payment_home', models.BooleanField(default=False, verbose_name='casa pagada')),
                ('payment_healthcare', models.BooleanField(default=False, verbose_name='seguro medico pagado')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=500, verbose_name='apellidos')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=False, verbose_name='usuario asignado')),
                ('date_born', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('english_level', models.IntegerField(verbose_name='nivel ingles')),
                ('empresa', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(verbose_name='Edad salario')),
                ('amount', models.IntegerField(verbose_name='salario bruto anual')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='salarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Salario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ofertas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Oferta'),
        ),
    ]
