# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20160918_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='date_born',
            field=models.DateField(verbose_name='fecha nacimiento'),
        ),
    ]
