# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_persona_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ett',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='localizacion',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='payment_healthcare',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='payment_home',
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(default='no name', max_length=250, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='prize_healthcare',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='prize_home',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='puesto',
            field=models.CharField(default='no name', max_length=250, verbose_name='puest de la oferta'),
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ofertas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ofertas',
            field=models.ManyToManyField(to='personas.Oferta'),
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='salarios',
        ),
        migrations.AddField(
            model_name='oferta',
            name='salarios',
            field=models.ManyToManyField(to='personas.Salario'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='nombre',
            field=models.CharField(default='no name', max_length=250, verbose_name='nombre'),
        ),
    ]
