# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20161016_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ofertas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ofertas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personas.Oferta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='prize_healthcare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='salarios',
        ),
        migrations.AddField(
            model_name='oferta',
            name='salarios',
            field=models.CharField(default='no name', max_length=900, verbose_name='Salarios Oferta'),
        ),
        migrations.DeleteModel(
            name='Salario',
        ),
    ]
