# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_auto_20161016_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ofertas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ofertas',
            field=models.ManyToManyField(blank=True, null=True, to='personas.Oferta'),
        ),
    ]
