# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_auto_20161016_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='empresa',
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa',
            field=models.ManyToManyField(blank=True, null=True, to='personas.Empresa'),
        ),
    ]
