# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_auto_20161017_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='hours_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='horas por semana'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='puesto',
            field=models.CharField(blank=True, default='no name', max_length=250, null=True, verbose_name='puest de la oferta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='salarios',
            field=models.CharField(blank=True, default='no name', max_length=900, null=True, verbose_name='Salarios Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='time_contract',
            field=models.IntegerField(blank=True, null=True, verbose_name='duracion contrato'),
        ),
    ]
