# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_auto_20161017_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='observaciones_prize_healthcare',
            field=models.CharField(blank=True, default='no name', max_length=250, null=True, verbose_name='observaciones seguro medico'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='observaciones_prize_home',
            field=models.CharField(blank=True, default='no name', max_length=250, null=True, verbose_name='observaciones precio casa'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='observaciones_time_contrato',
            field=models.CharField(blank=True, default='no name', max_length=250, null=True, verbose_name='observaciones duracion contrato'),
        ),
    ]
